classDiagram
    class Singleton {
        -static instance: Singleton
        -data: string
        -Singleton()
        +static getInstance() Singleton
        +getData() string
        +setData(data: string) void
    }
