classDiagram
    class Context {
        -state: State
        +setState(State)
        +request()
    }
    class State {
        <<interface>>
        +handle() void
    }
    class ConcreteStateA {
        +handle() void
    }
    class ConcreteStateB {
        +handle() void
    }
    Context o-- State
    State <|.. ConcreteStateA
    State <|.. ConcreteStateB